version: '3'
services:
  go:
    build:
      context: .
      dockerfile: ./Dockerfile
    entrypoint:
     - dockerize
     - -timeout
     - 60s
     - -wait
     - tcp://db:3306
    command: /bin/sh -c "./server"
    stdin_open: true
    tty: true
    ports:
      - 80:80
    depends_on:
      - "db"

  db:
    image: mysql:8.0.29
    environment:
      MYSQL_DATABASE: go_database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  adminer:
    image: adminer
    restart: always
    ports:
      - 3306:3306