openapi: "3.0.2"
info:
  title: Backend Tutorial
  version: "1.0"
servers:
  - url: http://localhost:8080
paths:
  /ping:
    get:
      tags:
        - Backend Tutorial
      summary: Return ping
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/message"
                example:
                  - message: ping
  /signin:
    post:
      tags:
        - Backend Tutorial
      summary: Sign in
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
            example:
              UserId: example_man
              Password: password
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/parameters/token'
                example:
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiZXhwIjoxNTQ3OTc0MDgyfQ.2Ye5_w1z3zpD4dSGdRp3s98ZipCNQqmsHRB9vioOx54
        400:
          description: Fail to sign in
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/message'
                example:
                  message: This user ID has been used
  /signup:
    post:
      tags:
        - Backend Tutorial
      summary: Sign up
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
            example:
              UserId: example_man
              Password: password
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/parameters/token'
                example:
                  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiZXhwIjoxNTQ3OTc0MDgyfQ.2Ye5_w1z3zpD4dSGdRp3s98ZipCNQqmsHRB9vioOx54
        400:
          description: Fail to sign in
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/message'
                example:
                  message: This user ID has been used
components:
  parameters:
    token:
      in: path
      name: token
      required: true
      schema:
        type: string
      description: json web token
  schemas:
    message:
      type: object
      required:
        - message
      properties:
        message: 
          type: string
    User:
      type: object
      required:
        - UserId
      properties:
        UserId:
          type: string 
        Password:
          type: string